INSERT INTO Amenities VALUES('SZÉP card');
INSERT INTO Amenities VALUES('Bank card');
INSERT INTO Amenities VALUES('Restaurant');
INSERT INTO Amenities VALUES('Breakfast');
INSERT INTO Amenities VALUES('Half-board');
INSERT INTO Amenities VALUES('Special food');
INSERT INTO Amenities VALUES('Lactose-free food');
INSERT INTO Amenities VALUES('Vegetarian food');
INSERT INTO Amenities VALUES('Barrier-free');
INSERT INTO Amenities VALUES('Baby friendly');
INSERT INTO Amenities VALUES('Balcony'||'/'||'Terrace');
INSERT INTO Amenities VALUES('Air conditioning');
INSERT INTO Amenities VALUES('TV');
INSERT INTO Amenities VALUES('WIFI');
INSERT INTO Amenities VALUES('Safe');
INSERT INTO Amenities VALUES('Cat'||'/'||'Dog');
INSERT INTO Amenities VALUES('Private parking');
INSERT INTO Amenities VALUES('Elevator');
INSERT INTO Amenities VALUES('Wellness');
INSERT INTO Amenities VALUES('Fitness');
INSERT INTO Amenities VALUES('Sports field');
