INSERT INTO Amenities VALUES(1,'SZÉP card');
INSERT INTO Amenities VALUES(2,'Bank card');
INSERT INTO Amenities VALUES(3,'Restaurant');
INSERT INTO Amenities VALUES(4,'Breakfast');
INSERT INTO Amenities VALUES(5,'Half-board');
INSERT INTO Amenities VALUES(6,'Special food');
INSERT INTO Amenities VALUES(7,'Lactose-free food');
INSERT INTO Amenities VALUES(8,'Vegetarian food');
INSERT INTO Amenities VALUES(9,'Barrier-free');
INSERT INTO Amenities VALUES(10,'Baby friendly');
INSERT INTO Amenities VALUES(11,'Balcony'||'/'||'Terrace');
INSERT INTO Amenities VALUES(12,'Air conditioning');
INSERT INTO Amenities VALUES(13,'TV');
INSERT INTO Amenities VALUES(14,'WIFI');
INSERT INTO Amenities VALUES(15,'Safe');
INSERT INTO Amenities VALUES(16,'Cat'||'/'||'Dog');
INSERT INTO Amenities VALUES(17,'Private parking');
INSERT INTO Amenities VALUES(18,'Street parking');
INSERT INTO Amenities VALUES(19,'Elevator');
INSERT INTO Amenities VALUES(20,'Wellness');
INSERT INTO Amenities VALUES(21,'Fitness');
INSERT INTO Amenities VALUES(22,'Sports field');
INSERT INTO Amenities VALUES(23,'Family rooms');
INSERT INTO Amenities VALUES(24,'Non-smoking rooms');
INSERT INTO Amenities VALUES(25,'Tea'||'/'||'Coffee maker');
INSERT INTO Amenities VALUES(26,'Microwave');
INSERT INTO Amenities VALUES(27,'Refrigerator');
INSERT INTO Amenities VALUES(28,'Electric kettle');
INSERT INTO Amenities VALUES(29,'Kitchenware');
INSERT INTO Amenities VALUES(30,'Toaster');
INSERT INTO Amenities VALUES(31,'Stovetop');
INSERT INTO Amenities VALUES(32,'Oven');
INSERT INTO Amenities VALUES(33,'Washing machine');
INSERT INTO Amenities VALUES(34,'Streaming service (like Netflix)');
INSERT INTO Amenities VALUES(35,'Outdoor furniture');
INSERT INTO Amenities VALUES(36,'Outdoor dining area');
INSERT INTO Amenities VALUES(37,'Heating');
INSERT INTO Amenities VALUES(38,'Smoke alarms');
INSERT INTO Amenities VALUES(39,'Socket near the bed');
INSERT INTO Amenities VALUES(40,'Garden');
