--DATA
--LISTINGTYPES
INSERT INTO LISTINGTYPES VALUES (1, 'Hotel');
INSERT INTO LISTINGTYPES VALUES (2,'Hostel');
INSERT INTO LISTINGTYPES VALUES (3, 'Apartment');
INSERT INTO LISTINGTYPES VALUES (4, 'GuestHouse');
INSERT INTO LISTINGTYPES VALUES (5, 'Vacation Home');
