INSERT INTO Amenities VALUES(1,'SZÉP card');
INSERT INTO Amenities VALUES(2,'Bank card');
INSERT INTO Amenities VALUES(3,'Restaurant');
INSERT INTO Amenities VALUES(4,'Breakfast');
INSERT INTO Amenities VALUES(5,'Half-board');
INSERT INTO Amenities VALUES(6,'Special food');
INSERT INTO Amenities VALUES(7,'Lactose-free food');
INSERT INTO Amenities VALUES(8,'Vegetarian food');
INSERT INTO Amenities VALUES(9,'Barrier-free');
INSERT INTO Amenities VALUES(10,'Baby friendly');
INSERT INTO Amenities VALUES(11,'Balcony'||'/'||'Terrace');
INSERT INTO Amenities VALUES(12,'Air conditioning');
INSERT INTO Amenities VALUES(13,'TV');
INSERT INTO Amenities VALUES(14,'WIFI');
INSERT INTO Amenities VALUES(15,'Safe');
INSERT INTO Amenities VALUES(16,'Cat'||'/'||'Dog');
INSERT INTO Amenities VALUES(17,'Private parking');
INSERT INTO Amenities VALUES(18,'Elevator');
INSERT INTO Amenities VALUES(19,'Wellness');
INSERT INTO Amenities VALUES(20,'Fitness');
INSERT INTO Amenities VALUES(21,'Sports field');
